# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.NETFramework.ReferenceAssemblies"; version = "1.0.2"; sha256 = "0i42rn8xmvhn08799manpym06kpw89qy9080myyy2ngy565pqh0a"; })
  (fetchNuGet { pname = "Microsoft.NETFramework.ReferenceAssemblies.net452"; version = "1.0.2"; sha256 = "02xpdaynfglblvi2brszspvz0rz3admzh35shnqgik6s1x75n82k"; })
  (fetchNuGet { pname = "Mono.Cecil"; version = "0.11.3"; sha256 = "0xcx7pk9y2n1hr15c0l1balzi69kw5gy8dk7sb8jwqyyvm35q4j3"; })
  (fetchNuGet { pname = "MonoMod"; version = "20.11.16.1"; sha256 = "1xn1dxqj4gl3yysr71hsjz0lshkb4znx833n7fananbgjlwxi9l2"; })
  (fetchNuGet { pname = "MonoMod.RuntimeDetour"; version = "20.11.16.1"; sha256 = "1agskmwm41334wlyz39cpg28nbrbrvh2466hkrvc8i71svk37f5q"; })
  (fetchNuGet { pname = "MonoMod.RuntimeDetour.HookGen"; version = "20.11.16.1"; sha256 = "0l9qp775p5lqgfm8hwlr4b8xxl2gs21m9wzjbyd8ch1qmblxffl1"; })
  (fetchNuGet { pname = "MonoMod.Utils"; version = "20.11.16.1"; sha256 = "0rfcam1rmc2m4n3h7bz5k9q9g014x5nl9808qnk1s7iwixpisywi"; })
  (fetchNuGet { pname = "Newtonsoft.Json"; version = "12.0.3"; sha256 = "17dzl305d835mzign8r15vkmav2hq8l6g7942dfjpnzr17wwl89x"; })
  (fetchNuGet { pname = "YamlDotNet"; version = "9.1.0"; sha256 = "0fcnw8plp1fl8nx5ykfbwq3qlsjpjzk65hfafj9dzj0vp4w0zcsr"; })
]
